/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_CROSS_COMPILER_PATH "/opt/ralink_tool/buildroot-gcc342/bin"
#undef  RT2880_ASIC_BOARD
#define RT3052_ASIC_BOARD 1
#define RT3052_MP2 1
#define P5_MAC_TO_NONE_MODE 1
#undef  P5_MAC_TO_PHY_MODE
#undef  P5_RGMII_TO_MAC_MODE
#undef  P5_MII_TO_MAC_MODE
#undef  P5_RMII_TO_MAC_MODE
#undef  MAC_TO_ICPLUS_MODE
#undef  MAC_TO_100PHY_MODE
#undef  MAC_TO_VITESSE_MODE
#undef  MAC_TO_GIGAPHY_MODE
#undef  ON_BOARD_NOR_FLASH_COMPONENT
#undef  ON_BOARD_NAND_FLASH_COMPONENT
#define ON_BOARD_SPI_FLASH_COMPONENT 1
#undef  DUAL_IMAGE_SUPPORT
#define UBOOT_RAM 1
#define TEXT_BASE 0x80200000
#undef  LAN_WAN_PARTITION
