# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2020
# Pawel Dembicki <paweldembicki@gmail.com>
#
# Based on Kirkwood support:
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>

obj-y	:= l-50.o
